http:
  routers:
    miniauth:
      rule: Host(`auth.example.com`)
      entryPoints:
        - web
      service: miniauth-svc
  services:
    miniauth-svc:
      loadBalancer:
        servers:
          - url: http://miniauth:4181